version: '3'

services:
  phpserver:
    image: php-mpdf:0.3
    container_name: phpserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

# sudo docker exec -it phpserver /bin/sh
